spring:
  application:
    name: library-manager

  datasource:
    url: jdbc:mysql://localhost:3300/library-manager_db
    username: stac
    password: secret
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 5000

logging:
  level:
    sql: info